export * from "./Login";
export * from "./Register";
export * from "./Profile";
export * from "./Friends";
export * from "./Feeds";
export * from "./FriendProfile";
export * from "./VerifyEmail";
export * from "./PrivacyPolicy";
export * from "./DataDeletion";